caddy:
  image: jmcarbo/rancher-caddy:latest
  ports:
    - 80:80
    - 443:443
  volumes:
    #- $PWD/test/Caddyfile:/etc/Caddyfile
    - /nfs/caddy:/root/.caddy
    - /nfs/caddy-logs:/logs
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: jmca.frontend=true
  command: /bin/sh
  environment:
    - HOSTS="cad3/isawesome;blu.bla.com:80=8000,bla.fff.com:80=9999@world;addd:80=9999"
  tty: true
  stdin: true
