caddy:
  image: jmcarbo/rancher-caddy:latest
  ports:
    - 80:80
    - 443:443
  volumes:
    #- $PWD/test/Caddyfile:/etc/Caddyfile
    - /nfs/caddy:/root/.caddy
    - /nfs/caddy-logs:/logs
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: jmca.frontend=true
  command: /bin/sh
  environment:
    - HOSTS=cad3/isawesome;isawesome.192.168.10.2.xip.io:80=80,isawesome2.192.168.10.2.xip.io:80=80
      @isawesome/rufus;rufus.192.168.10.2.xip.io:80=80,isawesome.193.145.244.254.xip.io:80=80
      @hello/world;hello.192.168.10.2.xip.io:80=80
      @marbiobanc.imim.es;marbiobanc.193.145.244.254.xip.io:80=80
  tty: true
  stdin: true
